# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='Unknown', max_length=255, verbose_name='Автор')),
                ('source', models.CharField(default='Author', max_length=255, verbose_name='Джерело')),
                ('content', models.TextField(verbose_name='Текст')),
                ('shingled_content', models.TextField(verbose_name='шинглований канонічний текст')),
                ('uniqueness', models.FloatField(default=-1, verbose_name='Унікальність')),
                ('upload_date', models.DateField(default=datetime.datetime(2019, 11, 27, 16, 27, 20, 78453), verbose_name='Дата завантаження')),
            ],
        ),
    ]
