# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='text',
            name='uniqueness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
