# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='shingled_content',
            field=models.TextField(null=True, verbose_name='шинглований канонічний текст'),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 16, 45, 16, 242414), verbose_name='Дата завантаження'),
        ),
    ]
