# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0002_auto_20190927_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='uniqueness',
            field=models.FloatField(default=0, verbose_name='Унікальність'),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата завантаження'),
        ),
    ]
