# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0003_auto_20190927_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(verbose_name='Дата завантаження'),
        ),
    ]
