# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0004_auto_20190927_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 27, 19, 14, 21, 9549), verbose_name='Дата завантаження'),
        ),
    ]
