# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0005_auto_20190927_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='upload_date',
        ),
    ]
