# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0005_auto_20191127_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 17, 7, 52, 53107), verbose_name='Дата завантаження'),
        ),
    ]
