# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-27 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0007_text_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 27, 19, 20, 0, 406015), verbose_name='Дата завантаження'),
        ),
    ]
