# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-28 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0008_auto_20190927_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 28, 19, 48, 42, 899329), verbose_name='Дата завантаження'),
        ),
    ]
