# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0009_auto_20191127_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 18, 50, 50, 293295), verbose_name='Дата завантаження'),
        ),
    ]
