# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-05 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0009_auto_20190928_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 5, 15, 34, 40, 615113), verbose_name='Дата завантаження'),
        ),
    ]
