# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-23 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0010_auto_20191005_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 23, 19, 13, 40, 172669), verbose_name='Дата завантаження'),
        ),
    ]
