# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0016_auto_20191130_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 30, 13, 32, 36, 891410, tzinfo=utc), verbose_name='Дата завантаження'),
        ),
    ]
