# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0020_auto_20191130_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='areas',
            field=models.TextField(default='', verbose_name='Діапазони'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
