# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0022_auto_20191201_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='areas',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
