# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0023_text_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='areas',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
