# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0029_auto_20200116_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='burrowed_content',
            field=models.TextField(default='[""]', verbose_name='Запозичений текст'),
        ),
    ]
