# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0031_text_shingle_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='shingle_dict',
            field=models.TextField(default='[""]', verbose_name='Словник шинглів'),
        ),
    ]
