# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-19 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0032_auto_20200119_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='shingled_content',
        ),
    ]
