# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0033_remove_text_shingled_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='burrowed_content',
            field=models.TextField(default='[{"": []}]', verbose_name='Запозичений текст'),
        ),
        migrations.AlterField(
            model_name='text',
            name='shingle_dict',
            field=models.TextField(default='{"": ""}', verbose_name='Словник шинглів'),
        ),
    ]
