# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TextProcessing', '0039_auto_20200131_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.CharField(default='Unknown', editable=False, max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='text',
            name='burrowed_content',
            field=models.TextField(default='{"": []}', editable=False, verbose_name='Запозичений текст'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(editable=False, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='text',
            name='shingle_dict',
            field=models.TextField(default='{"": ""}', editable=False, verbose_name='Словник шинглів'),
        ),
        migrations.AlterField(
            model_name='text',
            name='source',
            field=models.CharField(default='Author', editable=False, max_length=255, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='text',
            name='sources',
            field=models.TextField(default=-1, editable=False, verbose_name='Джерела'),
        ),
        migrations.AlterField(
            model_name='text',
            name='uniqueness',
            field=models.FloatField(default=-1, editable=False, verbose_name='Унікальність'),
        ),
        migrations.AlterField(
            model_name='text',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Дата завантаження'),
        ),
    ]
