version: "3"

services:
  antiplag-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./antiplag:/antiplag
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A Antiplag worker --pool=solo -l info
    volumes:
      - ./antiplag:/antiplag
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server
