version: "3"

services:
  antiplag-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./antiplag:/antiplag
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Antiplag worker --pool=solo -l info
    volumes:
      - ./antiplag:/antiplag
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server
