# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190926_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='author',
        ),
        migrations.RemoveField(
            model_name='text',
            name='uniqueness',
        ),
    ]
