# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20190926_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.CharField(default='1', max_length=255, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='text',
            name='uniqueness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
