# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190926_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='uniqueness',
            field=models.FloatField(default=0),
        ),
    ]
