# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190926_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Автор'),
        ),
    ]
